sections:
  main:
    display: Main
    fields:
      slug:
        display: Slug
        type: text
      template_list:
        fieldset: template
        type: partial
        display: Template
      available_only_english:
        type: toggle
        display: 'Available only in english'
taxonomies: true
title: Meta
hide: true
