name: ExtendedSection
version: 0.1
description: Sections on steroids
url: https://github.com/subpixel-ch/statamic-extended_section
developer: Rémy Böhler
developer_url: https://subpixel.ch

fieldtype_fields:
  background:
    type: select
    default: grey
    options:
      grey: default
      red: Red
      green: Green
      blue: Blue
      orange: Orange
      pink: Pink
      purple: Purple
      brown: Brown
      grey-30: Light grey
      grey-50: Grey
      grey-80: Dark grey
      black: Black
      carbon: Carbon
      stripes: Grey Stripes
      danger: Danger
      rainbow: Rainbow
